package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductParameterValue<M extends BaseProductParameterValue<M>> extends Model<M> implements IBean {

	public void setProduct(java.lang.Long product) {
		set("product", product);
	}

	public java.lang.Long getProduct() {
		return get("product");
	}

	public void setParameterValue(java.lang.String parameterValue) {
		set("parameter_value", parameterValue);
	}

	public java.lang.String getParameterValue() {
		return get("parameter_value");
	}

	public void setParameterValueKey(java.lang.Long parameterValueKey) {
		set("parameter_value_key", parameterValueKey);
	}

	public java.lang.Long getParameterValueKey() {
		return get("parameter_value_key");
	}

}
