package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberFavoriteProduct<M extends BaseMemberFavoriteProduct<M>> extends Model<M> implements IBean {

	public void setFavoriteMembers(java.lang.Long favoriteMembers) {
		set("favorite_members", favoriteMembers);
	}

	public java.lang.Long getFavoriteMembers() {
		return get("favorite_members");
	}

	public void setFavoriteProducts(java.lang.Long favoriteProducts) {
		set("favorite_products", favoriteProducts);
	}

	public java.lang.Long getFavoriteProducts() {
		return get("favorite_products");
	}

}
