package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermissionRole<M extends BasePermissionRole<M>> extends Model<M> implements IBean {

	public void setPermissions(java.lang.Long permissions) {
		set("permissions", permissions);
	}

	public java.lang.Long getPermissions() {
		return get("permissions");
	}

	public void setRoles(java.lang.Long roles) {
		set("roles", roles);
	}

	public java.lang.Long getRoles() {
		return get("roles");
	}

}
