package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductCategoryBrand<M extends BaseProductCategoryBrand<M>> extends Model<M> implements IBean {

	public void setProductCategories(java.lang.Long productCategories) {
		set("product_categories", productCategories);
	}

	public java.lang.Long getProductCategories() {
		return get("product_categories");
	}

	public void setBrands(java.lang.Long brands) {
		set("brands", brands);
	}

	public java.lang.Long getBrands() {
		return get("brands");
	}

}
