package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePluginConfigAttribute<M extends BasePluginConfigAttribute<M>> extends Model<M> implements IBean {

	public void setPluginConfig(java.lang.Long pluginConfig) {
		set("plugin_config", pluginConfig);
	}

	public java.lang.Long getPluginConfig() {
		return get("plugin_config");
	}

	public void setAttributes(java.lang.String attributes) {
		set("attributes", attributes);
	}

	public java.lang.String getAttributes() {
		return get("attributes");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

}
