package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionBrand<M extends BasePromotionBrand<M>> extends Model<M> implements IBean {

	public void setPromotions(java.lang.Long promotions) {
		set("promotions", promotions);
	}

	public java.lang.Long getPromotions() {
		return get("promotions");
	}

	public void setBrands(java.lang.Long brands) {
		set("brands", brands);
	}

	public java.lang.Long getBrands() {
		return get("brands");
	}

}
