package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminRole<M extends BaseAdminRole<M>> extends Model<M> implements IBean {

	public void setAdmins(java.lang.Long admins) {
		set("admins", admins);
	}

	public java.lang.Long getAdmins() {
		return get("admins");
	}

	public void setRoles(java.lang.Long roles) {
		set("roles", roles);
	}

	public java.lang.Long getRoles() {
		return get("roles");
	}

}
