package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShipping<M extends BaseShipping<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public void setShippingMethod(java.lang.String shippingMethod) {
		set("shipping_method", shippingMethod);
	}

	public java.lang.String getShippingMethod() {
		return get("shipping_method");
	}

	public void setDeliveryCorp(java.lang.String deliveryCorp) {
		set("delivery_corp", deliveryCorp);
	}

	public java.lang.String getDeliveryCorp() {
		return get("delivery_corp");
	}

	public void setDeliveryCorpUrl(java.lang.String deliveryCorpUrl) {
		set("delivery_corp_url", deliveryCorpUrl);
	}

	public java.lang.String getDeliveryCorpUrl() {
		return get("delivery_corp_url");
	}

	public void setDeliveryCorpCode(java.lang.String deliveryCorpCode) {
		set("delivery_corp_code", deliveryCorpCode);
	}

	public java.lang.String getDeliveryCorpCode() {
		return get("delivery_corp_code");
	}

	public void setTrackingNo(java.lang.String trackingNo) {
		set("tracking_no", trackingNo);
	}

	public java.lang.String getTrackingNo() {
		return get("tracking_no");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}

	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}

	public java.lang.String getConsignee() {
		return get("consignee");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return get("area");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
	}

	public java.lang.String getZipCode() {
		return get("zip_code");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}

	public java.lang.Long getOrderId() {
		return get("order_id");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setCreationDate(java.util.Date creationDate) {
		set("creation_date", creationDate);
	}

	public java.util.Date getCreationDate() {
		return get("creation_date");
	}

	public void setLastUpdatedBy(java.lang.String lastUpdatedBy) {
		set("last_updated_by", lastUpdatedBy);
	}

	public java.lang.String getLastUpdatedBy() {
		return get("last_updated_by");
	}

	public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
		set("last_updated_date", lastUpdatedDate);
	}

	public java.util.Date getLastUpdatedDate() {
		return get("last_updated_date");
	}

	public void setDeleteFlag(java.lang.Boolean deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Boolean getDeleteFlag() {
		return get("delete_flag");
	}

}
