package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductTag<M extends BaseProductTag<M>> extends Model<M> implements IBean {

	public void setProducts(java.lang.Long products) {
		set("products", products);
	}

	public java.lang.Long getProducts() {
		return get("products");
	}

	public void setTags(java.lang.Long tags) {
		set("tags", tags);
	}

	public java.lang.Long getTags() {
		return get("tags");
	}

}
