package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberAttributeOption<M extends BaseMemberAttributeOption<M>> extends Model<M> implements IBean {

	public void setMemberAttribute(java.lang.Long memberAttribute) {
		set("member_attribute", memberAttribute);
	}

	public java.lang.Long getMemberAttribute() {
		return get("member_attribute");
	}

	public void setOptions(java.lang.String options) {
		set("options", options);
	}

	public java.lang.String getOptions() {
		return get("options");
	}

}
