package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductMemberPrice<M extends BaseProductMemberPrice<M>> extends Model<M> implements IBean {

	public void setProduct(java.lang.Long product) {
		set("product", product);
	}

	public java.lang.Long getProduct() {
		return get("product");
	}

	public void setMemberPrice(java.math.BigDecimal memberPrice) {
		set("member_price", memberPrice);
	}

	public java.math.BigDecimal getMemberPrice() {
		return get("member_price");
	}

	public void setMemberPriceKey(java.lang.Long memberPriceKey) {
		set("member_price_key", memberPriceKey);
	}

	public java.lang.Long getMemberPriceKey() {
		return get("member_price_key");
	}

}
