package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShippingMethod<M extends BaseShippingMethod<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setFirstWeight(java.lang.Integer firstWeight) {
		set("first_weight", firstWeight);
	}

	public java.lang.Integer getFirstWeight() {
		return get("first_weight");
	}

	public void setContinueWeight(java.lang.Integer continueWeight) {
		set("continue_weight", continueWeight);
	}

	public java.lang.Integer getContinueWeight() {
		return get("continue_weight");
	}

	public void setFirstPrice(java.math.BigDecimal firstPrice) {
		set("first_price", firstPrice);
	}

	public java.math.BigDecimal getFirstPrice() {
		return get("first_price");
	}

	public void setContinuePrice(java.math.BigDecimal continuePrice) {
		set("continue_price", continuePrice);
	}

	public java.math.BigDecimal getContinuePrice() {
		return get("continue_price");
	}

	public void setOrders(java.lang.Integer orders) {
		set("orders", orders);
	}

	public java.lang.Integer getOrders() {
		return get("orders");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setDefaultDeliveryCorpId(java.lang.Long defaultDeliveryCorpId) {
		set("default_delivery_corp_id", defaultDeliveryCorpId);
	}

	public java.lang.Long getDefaultDeliveryCorpId() {
		return get("default_delivery_corp_id");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setCreationDate(java.util.Date creationDate) {
		set("creation_date", creationDate);
	}

	public java.util.Date getCreationDate() {
		return get("creation_date");
	}

	public void setLastUpdatedBy(java.lang.String lastUpdatedBy) {
		set("last_updated_by", lastUpdatedBy);
	}

	public java.lang.String getLastUpdatedBy() {
		return get("last_updated_by");
	}

	public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
		set("last_updated_date", lastUpdatedDate);
	}

	public java.util.Date getLastUpdatedDate() {
		return get("last_updated_date");
	}

	public void setDeleteFlag(java.lang.Boolean deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Boolean getDeleteFlag() {
		return get("delete_flag");
	}

}
