package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionProduct<M extends BasePromotionProduct<M>> extends Model<M> implements IBean {

	public void setPromotions(java.lang.Long promotions) {
		set("promotions", promotions);
	}

	public java.lang.Long getPromotions() {
		return get("promotions");
	}

	public void setProducts(java.lang.Long products) {
		set("products", products);
	}

	public java.lang.Long getProducts() {
		return get("products");
	}

}
