package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderCoupon<M extends BaseOrderCoupon<M>> extends Model<M> implements IBean {

	public void setOrders(java.lang.Long orders) {
		set("orders", orders);
	}

	public java.lang.Long getOrders() {
		return get("orders");
	}

	public void setCoupons(java.lang.Long coupons) {
		set("coupons", coupons);
	}

	public java.lang.Long getCoupons() {
		return get("coupons");
	}

}
