package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductSpecificationValue<M extends BaseProductSpecificationValue<M>> extends Model<M> implements IBean {

	public void setProducts(java.lang.Long products) {
		set("products", products);
	}

	public java.lang.Long getProducts() {
		return get("products");
	}

	public void setSpecificationValues(java.lang.Long specificationValues) {
		set("specification_values", specificationValues);
	}

	public java.lang.Long getSpecificationValues() {
		return get("specification_values");
	}

}
