package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegisterCode<M extends BaseRegisterCode<M>> extends Model<M> implements IBean {

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setSmsCode(java.lang.String smsCode) {
		set("sms_code", smsCode);
	}

	public java.lang.String getSmsCode() {
		return get("sms_code");
	}

	public void setOp(java.lang.String op) {
		set("op", op);
	}

	public java.lang.String getOp() {
		return get("op");
	}

	public void setCreationDate(java.util.Date creationDate) {
		set("creation_date", creationDate);
	}

	public java.util.Date getCreationDate() {
		return get("creation_date");
	}

	public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
		set("last_updated_date", lastUpdatedDate);
	}

	public java.util.Date getLastUpdatedDate() {
		return get("last_updated_date");
	}

	public void setExpirationDate(java.util.Date expirationDate) {
		set("expiration_date", expirationDate);
	}

	public java.util.Date getExpirationDate() {
		return get("expiration_date");
	}

}
