package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
	}

	public java.lang.Integer getOrderStatus() {
		return get("order_status");
	}

	public void setPaymentStatus(java.lang.Integer paymentStatus) {
		set("payment_status", paymentStatus);
	}

	public java.lang.Integer getPaymentStatus() {
		return get("payment_status");
	}

	public void setShippingStatus(java.lang.Integer shippingStatus) {
		set("shipping_status", shippingStatus);
	}

	public java.lang.Integer getShippingStatus() {
		return get("shipping_status");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}

	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setPromotionDiscount(java.math.BigDecimal promotionDiscount) {
		set("promotion_discount", promotionDiscount);
	}

	public java.math.BigDecimal getPromotionDiscount() {
		return get("promotion_discount");
	}

	public void setCouponDiscount(java.math.BigDecimal couponDiscount) {
		set("coupon_discount", couponDiscount);
	}

	public java.math.BigDecimal getCouponDiscount() {
		return get("coupon_discount");
	}

	public void setOffsetAmount(java.math.BigDecimal offsetAmount) {
		set("offset_amount", offsetAmount);
	}

	public java.math.BigDecimal getOffsetAmount() {
		return get("offset_amount");
	}

	public void setAmountPaid(java.math.BigDecimal amountPaid) {
		set("amount_paid", amountPaid);
	}

	public java.math.BigDecimal getAmountPaid() {
		return get("amount_paid");
	}

	public void setPoint(java.lang.Long point) {
		set("point", point);
	}

	public java.lang.Long getPoint() {
		return get("point");
	}

	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}

	public java.lang.String getConsignee() {
		return get("consignee");
	}

	public void setAreaName(java.lang.String areaName) {
		set("area_name", areaName);
	}

	public java.lang.String getAreaName() {
		return get("area_name");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
	}

	public java.lang.String getZipCode() {
		return get("zip_code");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setIsInvoice(java.lang.Boolean isInvoice) {
		set("is_invoice", isInvoice);
	}

	public java.lang.Boolean getIsInvoice() {
		return get("is_invoice");
	}

	public void setInvoiceTitle(java.lang.String invoiceTitle) {
		set("invoice_title", invoiceTitle);
	}

	public java.lang.String getInvoiceTitle() {
		return get("invoice_title");
	}

	public void setTax(java.math.BigDecimal tax) {
		set("tax", tax);
	}

	public java.math.BigDecimal getTax() {
		return get("tax");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public void setPromotion(java.lang.String promotion) {
		set("promotion", promotion);
	}

	public java.lang.String getPromotion() {
		return get("promotion");
	}

	public void setExpire(java.util.Date expire) {
		set("expire", expire);
	}

	public java.util.Date getExpire() {
		return get("expire");
	}

	public void setLockExpire(java.util.Date lockExpire) {
		set("lock_expire", lockExpire);
	}

	public java.util.Date getLockExpire() {
		return get("lock_expire");
	}

	public void setIsAllocatedStock(java.lang.Boolean isAllocatedStock) {
		set("is_allocated_stock", isAllocatedStock);
	}

	public java.lang.Boolean getIsAllocatedStock() {
		return get("is_allocated_stock");
	}

	public void setPaymentMethodName(java.lang.String paymentMethodName) {
		set("payment_method_name", paymentMethodName);
	}

	public java.lang.String getPaymentMethodName() {
		return get("payment_method_name");
	}

	public void setShippingMethodName(java.lang.String shippingMethodName) {
		set("shipping_method_name", shippingMethodName);
	}

	public java.lang.String getShippingMethodName() {
		return get("shipping_method_name");
	}

	public void setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
	}

	public java.lang.Long getAreaId() {
		return get("area_id");
	}

	public void setPaymentMethodId(java.lang.Long paymentMethodId) {
		set("payment_method_id", paymentMethodId);
	}

	public java.lang.Long getPaymentMethodId() {
		return get("payment_method_id");
	}

	public void setShippingMethodId(java.lang.Long shippingMethodId) {
		set("shipping_method_id", shippingMethodId);
	}

	public java.lang.Long getShippingMethodId() {
		return get("shipping_method_id");
	}

	public void setOperatorId(java.lang.Long operatorId) {
		set("operator_id", operatorId);
	}

	public java.lang.Long getOperatorId() {
		return get("operator_id");
	}

	public void setMemberId(java.lang.Long memberId) {
		set("member_id", memberId);
	}

	public java.lang.Long getMemberId() {
		return get("member_id");
	}

	public void setCouponCode(java.lang.Long couponCode) {
		set("coupon_code", couponCode);
	}

	public java.lang.Long getCouponCode() {
		return get("coupon_code");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setCreationDate(java.util.Date creationDate) {
		set("creation_date", creationDate);
	}

	public java.util.Date getCreationDate() {
		return get("creation_date");
	}

	public void setLastUpdatedBy(java.lang.String lastUpdatedBy) {
		set("last_updated_by", lastUpdatedBy);
	}

	public java.lang.String getLastUpdatedBy() {
		return get("last_updated_by");
	}

	public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
		set("last_updated_date", lastUpdatedDate);
	}

	public java.util.Date getLastUpdatedDate() {
		return get("last_updated_date");
	}

	public void setDeleteFlag(java.lang.Boolean deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.Boolean getDeleteFlag() {
		return get("delete_flag");
	}

}
