package com.jfinalshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttributeOption<M extends BaseAttributeOption<M>> extends Model<M> implements IBean {

	public void setAttribute(java.lang.Long attribute) {
		set("attribute", attribute);
	}

	public java.lang.Long getAttribute() {
		return get("attribute");
	}

	public void setOptions(java.lang.String options) {
		set("options", options);
	}

	public java.lang.String getOptions() {
		return get("options");
	}

}
