package com.jfinalshop.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ad", "id", Ad.class);
		arp.addMapping("ad_position", "id", AdPosition.class);
		arp.addMapping("admin", "id", Admin.class);
		// Composite Primary Key order: admins,roles
		arp.addMapping("admin_role", "admins,roles", AdminRole.class);
		arp.addMapping("area", "id", Area.class);
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("article_category", "id", ArticleCategory.class);
		// Composite Primary Key order: articles,tags
		arp.addMapping("article_tag", "articles,tags", ArticleTag.class);
		arp.addMapping("attribute", "id", Attribute.class);
		arp.addMapping("attribute_option", AttributeOption.class);
		arp.addMapping("brand", "id", Brand.class);
		arp.addMapping("cart", "id", Cart.class);
		arp.addMapping("cart_item", "id", CartItem.class);
		arp.addMapping("consultation", "id", Consultation.class);
		arp.addMapping("coupon", "id", Coupon.class);
		arp.addMapping("coupon_code", "id", CouponCode.class);
		arp.addMapping("delivery_center", "id", DeliveryCenter.class);
		arp.addMapping("delivery_corp", "id", DeliveryCorp.class);
		arp.addMapping("delivery_template", "id", DeliveryTemplate.class);
		arp.addMapping("deposit", "id", Deposit.class);
		arp.addMapping("feedback", "id", Feedback.class);
		arp.addMapping("friend_link", "id", FriendLink.class);
		arp.addMapping("gift_item", "id", GiftItem.class);
		arp.addMapping("goods", "id", Goods.class);
		arp.addMapping("log", "id", Log.class);
		arp.addMapping("member", "id", Member.class);
		arp.addMapping("member_attribute", "id", MemberAttribute.class);
		arp.addMapping("member_attribute_option", MemberAttributeOption.class);
		// Composite Primary Key order: favorite_members,favorite_products
		arp.addMapping("member_favorite_product", "favorite_members,favorite_products", MemberFavoriteProduct.class);
		arp.addMapping("member_rank", "id", MemberRank.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("navigation", "id", Navigation.class);
		arp.addMapping("order", "id", Order.class);
		arp.addMapping("order_coupon", OrderCoupon.class);
		arp.addMapping("order_item", "id", OrderItem.class);
		arp.addMapping("order_log", "id", OrderLog.class);
		arp.addMapping("parameter", "id", Parameter.class);
		arp.addMapping("parameter_group", "id", ParameterGroup.class);
		arp.addMapping("payment", "id", Payment.class);
		arp.addMapping("payment_method", "id", PaymentMethod.class);
		// Composite Primary Key order: payment_methods,shipping_methods
		arp.addMapping("payment_shipping_method", "payment_methods,shipping_methods", PaymentShippingMethod.class);
		arp.addMapping("permission", "id", Permission.class);
		// Composite Primary Key order: permissions,roles
		arp.addMapping("permission_role", "permissions,roles", PermissionRole.class);
		arp.addMapping("plugin_config", "id", PluginConfig.class);
		// Composite Primary Key order: name,plugin_config
		arp.addMapping("plugin_config_attribute", "name,plugin_config", PluginConfigAttribute.class);
		arp.addMapping("product", "id", Product.class);
		arp.addMapping("product_category", "id", ProductCategory.class);
		// Composite Primary Key order: brands,product_categories
		arp.addMapping("product_category_brand", "brands,product_categories", ProductCategoryBrand.class);
		arp.addMapping("product_image", ProductImage.class);
		// Composite Primary Key order: member_price_key,product
		arp.addMapping("product_member_price", "member_price_key,product", ProductMemberPrice.class);
		arp.addMapping("product_notify", "id", ProductNotify.class);
		// Composite Primary Key order: parameter_value_key,product
		arp.addMapping("product_parameter_value", "parameter_value_key,product", ProductParameterValue.class);
		// Composite Primary Key order: products,specifications
		arp.addMapping("product_specification", "products,specifications", ProductSpecification.class);
		// Composite Primary Key order: products,specification_values
		arp.addMapping("product_specification_value", "products,specification_values", ProductSpecificationValue.class);
		// Composite Primary Key order: products,tags
		arp.addMapping("product_tag", "products,tags", ProductTag.class);
		arp.addMapping("promotion", "id", Promotion.class);
		// Composite Primary Key order: brands,promotions
		arp.addMapping("promotion_brand", "brands,promotions", PromotionBrand.class);
		// Composite Primary Key order: coupons,promotions
		arp.addMapping("promotion_coupon", "coupons,promotions", PromotionCoupon.class);
		// Composite Primary Key order: member_ranks,promotions
		arp.addMapping("promotion_member_rank", "member_ranks,promotions", PromotionMemberRank.class);
		// Composite Primary Key order: products,promotions
		arp.addMapping("promotion_product", "products,promotions", PromotionProduct.class);
		// Composite Primary Key order: product_categories,promotions
		arp.addMapping("promotion_product_category", "product_categories,promotions", PromotionProductCategory.class);
		arp.addMapping("receiver", "id", Receiver.class);
		arp.addMapping("refunds", "id", Refunds.class);
		arp.addMapping("register_code", "mobile", RegisterCode.class);
		arp.addMapping("returns", "id", Returns.class);
		arp.addMapping("returns_item", "id", ReturnsItem.class);
		arp.addMapping("review", "id", Review.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("seo", "id", Seo.class);
		arp.addMapping("shipping", "id", Shipping.class);
		arp.addMapping("shipping_item", "id", ShippingItem.class);
		arp.addMapping("shipping_method", "id", ShippingMethod.class);
		arp.addMapping("sn", "id", Sn.class);
		arp.addMapping("specification", "id", Specification.class);
		arp.addMapping("specification_value", "id", SpecificationValue.class);
		arp.addMapping("tag", "id", Tag.class);
	}
}

