package com.jfinalshop.model;

import com.jfinalshop.model.base.BaseFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedback extends BaseFeedback<Feedback> {
	public static final Feedback dao = new Feedback();
}
