package com.jfinalshop.model;

import org.apache.commons.lang3.builder.CompareToBuilder;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.upload.UploadFile;
import com.jfinalshop.model.base.BaseProductImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductImage extends BaseProductImage<ProductImage> implements Comparable<ProductImage>{
	public static final ProductImage dao = new ProductImage();

	/** 文件 */
	private UploadFile file;
	
	public UploadFile getUploadFile() {
		return file;
	}

	public void setUploadFile(UploadFile uploadFile) {
		this.file = uploadFile;
	}

	public int compareTo(ProductImage productImage) {
		return new CompareToBuilder().append(getOrders(), productImage.getOrders()).toComparison();
	}
	
	/**
	 * 根据产品ID删除
	 * @param adminId
	 * @return
	 */
	public boolean delete(Long products) {
		return Db.deleteById("product_image", "product_id", products);
	}
}
